defmodule Backend.CustomerOrders.NpdSync do
  @moduledoc """
  Upsert a CustomerOrder from an NPD formulation-sync payload.

  Called via the integration surface (``POST /api/integration/customer-orders/sync``)
  every time NPD saves a version of a formulation. The identity key
  is ``npd_formulation_uuid`` — new formulations become fresh draft
  COs with ``uuid = npd_formulation_uuid`` planted so the URL matches
  on both sides.

  R&D projects don't have a customer yet, so a per-company "NPD
  Placeholder" customer is auto-provisioned on first sync. When the
  scientist later links a real customer via the proposal flow on NPD,
  a subsequent sync will overwrite ``customer_id``.
  """

  import Ecto.Query

  alias Backend.CustomerOrders.CustomerOrder
  alias Backend.CustomerOrders.CustomerOrderLine
  alias Backend.Customers.Customer
  alias Backend.Items.Item
  alias Backend.Repo

  @placeholder_customer_name "NPD Placeholder"

  @doc """
  Upsert a CO from the NPD payload. Payload shape:

      %{
        "npd_formulation_uuid" => "…uuid…",
        "name"                 => "Alex Gummies",
        "code"                 => "MA01421",
        "notes"                => "…" (optional)
      }

  Returns:

    * ``{:ok, %CustomerOrder{}}`` — inserted or updated.
    * ``{:error, changeset | reason}`` — validation / constraint / DB.

  Runs in a transaction so the placeholder-customer bootstrap + the CO
  upsert both succeed or both fail.
  """
  def upsert_from_npd(company_id, params) when is_integer(company_id) do
    with {:ok, npd_uuid} <- extract_uuid(params) do
      Repo.transaction(fn ->
        # Resolve the effective ``customer_id`` for this CO in the
        # same transaction as the CO upsert so the FK is set atomically
        # with the identity fields. When NPD sends a customer link we
        # find-or-create a shell PSP customer; when it sends an
        # empty display name we snap back to the per-tenant placeholder.
        placeholder = ensure_placeholder_customer(company_id)
        active_customer = resolve_customer(company_id, placeholder, params)

        case Repo.get_by(CustomerOrder,
               company_id: company_id,
               npd_formulation_uuid: npd_uuid
             ) do
          nil ->
            insert_new(company_id, active_customer, npd_uuid, params)

          existing ->
            update_existing(existing, active_customer, params)
        end
      end)
      |> case do
        {:ok, {:ok, co}} -> {:ok, co}
        {:ok, {:error, cs}} -> {:error, cs}
        {:error, reason} -> {:error, reason}
      end
    end
  end

  # ----- Insert / update paths ------------------------------------

  defp insert_new(company_id, active_customer, npd_uuid, params) do
    now = DateTime.utc_now() |> DateTime.truncate(:second)

    attrs = %{
      company_id: company_id,
      customer_id: active_customer.id,
      currency_code: active_customer.currency_code || "GBP",
      # Stash the formulation's display name + code into
      # `customer_reference` so the PSP kanban / project detail can
      # show what the scientist called the project on NPD — without
      # this the card falls back to "NPD Placeholder", the customer's
      # name, which is meaningless for R&D.
      customer_reference: reference_for(params),
      notes: sanitize(params["notes"] || params[:notes]),
      inserted_at: now,
      updated_at: now
    }

    # `CustomerOrder.uuid` is autogenerated by default; we override
    # here to match the NPD formulation UUID exactly. This is what
    # makes ``/projects/<npd-uuid>`` open the same entity on both
    # sides without a cross-reference table.
    #
    # ``npd_formulation_uuid`` / ``status`` / the mirrored NPD team
    # fields are not in the base `changeset/2` cast list (none of
    # them are operator-editable on PSP), so we `put_change` them
    # here — otherwise the values silently drop and the CO lands in
    # the `:setup` bucket instead of `:r_and_d`, and the team fields
    # never populate.
    %CustomerOrder{uuid: npd_uuid}
    |> CustomerOrder.changeset(attrs)
    |> Ecto.Changeset.put_change(:npd_formulation_uuid, npd_uuid)
    |> Ecto.Changeset.put_change(:status, "draft")
    |> put_npd_team(params)
    |> put_customer_delivery_address(params)
    |> Repo.insert()
  end

  defp update_existing(%CustomerOrder{} = existing, active_customer, params) do
    attrs = %{
      # Only touch operator-neutral display fields on re-sync — the
      # scientist may have renamed the formulation on NPD, so let the
      # PSP-side title track that. Everything downstream (status,
      # totals) is owned by the PSP flow once the CO moves past
      # draft, so we leave those alone.
      customer_reference:
        reference_for(params) || existing.customer_reference,
      notes: sanitize(params["notes"] || params[:notes]) || existing.notes
    }

    # Swap the ``customer_id`` FK only while the CO is still a draft.
    # Once Sales has submitted it (pending_approver / confirmed / …)
    # the customer FK is legally owned by the CO — a downstream NPD
    # relink shouldn't retroactively rewrite an approved order's
    # billing party.
    changeset =
      existing
      |> CustomerOrder.changeset(attrs)
      |> put_npd_team(params)
      |> put_customer_delivery_address(params, existing.status)

    changeset =
      if existing.status == "draft" and existing.customer_id != active_customer.id do
        Ecto.Changeset.put_change(changeset, :customer_id, active_customer.id)
      else
        changeset
      end

    Repo.update(changeset)
  end

  # Mirror the R&D team + deep-link fields from NPD's payload. Applied
  # to both insert + update paths so a role reassignment on NPD flows
  # to PSP on the next sync. Falls back to the existing values (or
  # nil) when a field is omitted — that way a re-sync from an older
  # NPD that doesn't yet send `app_url` doesn't wipe a value we
  # already have.
  defp put_npd_team(changeset, params) do
    lead = sanitize(params["lead_scientist_name"] || params[:lead_scientist_name])
    sales = sanitize(params["sales_person_name"] || params[:sales_person_name])
    app_url = sanitize(params["app_url"] || params[:app_url])

    changeset
    |> maybe_put(:npd_lead_scientist_name, lead)
    |> maybe_put(:npd_sales_person_name, sales)
    |> maybe_put(:npd_app_url, app_url)
    |> put_npd_customer(params)
    |> put_npd_cff(params)
    |> put_npd_spec(params)
  end

  # CFF submission link. Same shape as ``put_npd_spec/2``:
  #
  #   * ``cff_state: "cleared"``  →  explicit nil-out on every column.
  #     NPD ships this when the scientist detaches the CFF from the
  #     project via ``detach_from_project``.
  #   * anything else, individual keys omitted  →  leave existing
  #     values alone (so a plain ``save_version`` re-sync doesn't
  #     wipe a link that's still valid).
  defp put_npd_cff(changeset, params) do
    case params["cff_state"] || params[:cff_state] do
      "cleared" ->
        changeset
        |> Ecto.Changeset.put_change(:npd_cff_uuid, nil)
        |> Ecto.Changeset.put_change(:npd_cff_url, nil)
        |> Ecto.Changeset.put_change(:npd_cff_submitter_name, nil)
        |> Ecto.Changeset.put_change(:npd_cff_submitter_email, nil)

      _ ->
        changeset
        |> maybe_put_uuid(:npd_cff_uuid, params["cff_uuid"] || params[:cff_uuid])
        |> maybe_put(:npd_cff_url, sanitize(params["cff_url"] || params[:cff_url]))
        |> maybe_put(:npd_cff_submitter_name, sanitize(params["cff_submitter_name"] || params[:cff_submitter_name]))
        |> maybe_put(:npd_cff_submitter_email, sanitize(params["cff_submitter_email"] || params[:cff_submitter_email]))
    end
  end

  # Customer link from NPD. Explicit-clear semantics: NPD ships an
  # empty ``customer_display_name`` on unlink, so we treat empty
  # strings as "wipe" (via ``put_change(nil)``) rather than "no
  # change". Missing keys still fall through unchanged.
  defp put_npd_customer(changeset, params) do
    raw_name = params["customer_display_name"] || params[:customer_display_name]
    raw_uuid = params["customer_uuid"] || params[:customer_uuid]

    changeset
    |> apply_customer_field(:npd_customer_display_name, raw_name)
    |> apply_customer_uuid(raw_uuid)
  end

  defp apply_customer_field(changeset, _field, nil), do: changeset

  defp apply_customer_field(changeset, field, ""),
    do: Ecto.Changeset.put_change(changeset, field, nil)

  defp apply_customer_field(changeset, field, value) when is_binary(value),
    do: Ecto.Changeset.put_change(changeset, field, String.trim(value))

  defp apply_customer_field(changeset, _field, _), do: changeset

  defp apply_customer_uuid(changeset, nil), do: changeset

  defp apply_customer_uuid(changeset, ""),
    do: Ecto.Changeset.put_change(changeset, :npd_customer_uuid, nil)

  defp apply_customer_uuid(changeset, raw) when is_binary(raw) do
    case Ecto.UUID.cast(raw) do
      {:ok, uuid} -> Ecto.Changeset.put_change(changeset, :npd_customer_uuid, uuid)
      :error -> changeset
    end
  end

  defp apply_customer_uuid(changeset, _), do: changeset

  # Spec-sheet identity + sign-off. Fires from NPD's
  # ``transition_status(status=approved)`` service alongside the
  # regular save_version sync — that's the "director signed, spec
  # is quotable" moment and gates the phase move to
  # ``:awaiting_proposal`` on the PSP wizard. Individual fields fall
  # through nil so unrelated re-syncs (which don't carry spec data)
  # don't wipe the values we already have.
  #
  # Special-case: NPD signals ``spec_state: "cleared"`` when a
  # previously-approved sheet has been reverted back to draft /
  # rejected. In that case we explicitly wipe every ``npd_spec_*``
  # column via ``put_change(:field, nil)`` so PSP's phase-derivation
  # sees no ``npd_spec_approved_at`` and the wizard drops back from
  # ``:awaiting_proposal`` to ``:r_and_d``.
  defp put_npd_spec(changeset, params) do
    case params["spec_state"] || params[:spec_state] do
      "cleared" ->
        changeset
        |> Ecto.Changeset.put_change(:npd_spec_sheet_uuid, nil)
        |> Ecto.Changeset.put_change(:npd_spec_sheet_url, nil)
        |> Ecto.Changeset.put_change(:npd_spec_prepared_by_name, nil)
        |> Ecto.Changeset.put_change(:npd_spec_prepared_at, nil)
        |> Ecto.Changeset.put_change(:npd_spec_director_name, nil)
        |> Ecto.Changeset.put_change(:npd_spec_approved_at, nil)

      _ ->
        changeset
        |> maybe_put_uuid(:npd_spec_sheet_uuid, params["spec_sheet_uuid"] || params[:spec_sheet_uuid])
        |> maybe_put(:npd_spec_sheet_url, sanitize(params["spec_sheet_url"] || params[:spec_sheet_url]))
        |> maybe_put(:npd_spec_prepared_by_name, sanitize(params["spec_prepared_by_name"] || params[:spec_prepared_by_name]))
        |> maybe_put_dt(:npd_spec_prepared_at, params["spec_prepared_at"] || params[:spec_prepared_at])
        |> maybe_put(:npd_spec_director_name, sanitize(params["spec_director_name"] || params[:spec_director_name]))
        |> maybe_put_dt(:npd_spec_approved_at, params["spec_approved_at"] || params[:spec_approved_at])
    end
  end

  defp maybe_put(changeset, _field, nil), do: changeset
  defp maybe_put(changeset, field, value), do: Ecto.Changeset.put_change(changeset, field, value)

  defp maybe_put_uuid(changeset, _field, nil), do: changeset
  defp maybe_put_uuid(changeset, _field, ""), do: changeset

  defp maybe_put_uuid(changeset, field, raw) when is_binary(raw) do
    case Ecto.UUID.cast(raw) do
      {:ok, uuid} -> Ecto.Changeset.put_change(changeset, field, uuid)
      :error -> changeset
    end
  end

  defp maybe_put_uuid(changeset, _field, _), do: changeset

  defp maybe_put_dt(changeset, _field, nil), do: changeset
  defp maybe_put_dt(changeset, _field, ""), do: changeset

  defp maybe_put_dt(changeset, field, raw) when is_binary(raw) do
    # Accepts ISO-8601 strings (``2026-07-30T13:53:15Z``). Missing /
    # malformed values are silently ignored so a mis-typed payload
    # doesn't blow up the whole sync.
    case DateTime.from_iso8601(raw) do
      {:ok, dt, _offset} ->
        Ecto.Changeset.put_change(changeset, field, DateTime.truncate(dt, :second))

      {:error, _} ->
        changeset
    end
  end

  defp maybe_put_dt(changeset, field, %DateTime{} = dt),
    do: Ecto.Changeset.put_change(changeset, field, DateTime.truncate(dt, :second))

  defp maybe_put_dt(changeset, _field, _), do: changeset

  # Build the "display name" for the CO from the NPD payload's
  # `name` + `code`. Trims + collapses; returns nil when there's
  # nothing to show so the fallback (existing value / customer name)
  # takes over.
  defp reference_for(params) do
    name = sanitize(params["name"] || params[:name])
    code = sanitize(params["code"] || params[:code])

    cond do
      name && code -> "#{name} (#{code})"
      name -> name
      code -> code
      true -> nil
    end
  end

  # ----- Customer resolution --------------------------------------
  #
  # Pick the customer this CO should point at based on the sync payload:
  #
  #   * Empty ``customer_display_name`` OR no ``customer_uuid``  →
  #     the NPD project has no linked client (or was just unlinked).
  #     Fall back to the per-tenant placeholder so the CO's FK stays
  #     valid.
  #
  #   * Non-empty  →  find-or-create a real PSP customer mirroring the
  #     NPD row. Dedupe order:
  #
  #       1. ``customers.npd_source_uuid = <uuid>`` — exact identity
  #          match, wins even if the operator has since renamed the
  #          customer on PSP.
  #       2. ``customers.name = <display_name>`` — soft dedupe against
  #          an existing PSP-native row with the same name; back-fills
  #          ``npd_source_uuid`` so future syncs skip straight to
  #          step 1.
  #       3. New customer — landed as ``approval_status: draft`` since
  #          the PSP qualification flow still owns approval.

  defp resolve_customer(company_id, placeholder, params) do
    display = sanitize(params["customer_display_name"] || params[:customer_display_name])
    uuid = sanitize(params["customer_uuid"] || params[:customer_uuid])

    if is_nil(display) or is_nil(uuid) do
      placeholder
    else
      case Ecto.UUID.cast(uuid) do
        {:ok, cast_uuid} ->
          find_or_create_customer(company_id, cast_uuid, display, params) ||
            placeholder

        :error ->
          placeholder
      end
    end
  end

  defp find_or_create_customer(company_id, npd_uuid, display, params) do
    existing_by_uuid =
      Repo.one(
        from c in Customer,
          where: c.company_id == ^company_id and c.npd_source_uuid == ^npd_uuid,
          limit: 1
      )

    case existing_by_uuid do
      %Customer{} = c ->
        c

      nil ->
        by_name =
          Repo.one(
            from c in Customer,
              where: c.company_id == ^company_id and c.name == ^display,
              limit: 1
          )

        case by_name do
          %Customer{} = c ->
            # Back-fill the identity marker so subsequent syncs land
            # via the fast path.
            c
            |> Ecto.Changeset.change(npd_source_uuid: npd_uuid)
            |> Repo.update!()

          nil ->
            insert_customer(company_id, npd_uuid, display, params)
        end
    end
  end

  defp insert_customer(company_id, npd_uuid, display, params) do
    attrs = %{
      company_id: company_id,
      name: display,
      legal_name: display,
      contact_name: sanitize(params["customer_contact_name"] || params[:customer_contact_name]) || "",
      currency_code: "GBP"
    }

    {:ok, inserted} =
      %Customer{}
      |> Customer.changeset(attrs)
      |> Ecto.Changeset.put_change(:npd_source_uuid, npd_uuid)
      |> Repo.insert()

    inserted
  end

  # ----- Placeholder customer -------------------------------------

  defp ensure_placeholder_customer(company_id) do
    case Repo.one(
           from c in Customer,
             where:
               c.company_id == ^company_id and c.name == ^@placeholder_customer_name,
             limit: 1
         ) do
      %Customer{} = c ->
        c

      nil ->
        # Minimal-viable customer — a placeholder that carries no real
        # contact data. Sales replaces this via the proposal flow once
        # a customer is actually linked. `changeset/2` requires only
        # ``company_id`` + ``name`` so we can skip the rest.
        {:ok, customer} =
          %Customer{}
          |> Customer.changeset(%{
            company_id: company_id,
            name: @placeholder_customer_name,
            currency_code: "GBP"
          })
          |> Repo.insert()

        customer
    end
  end

  # ----- Helpers --------------------------------------------------

  defp extract_uuid(params) do
    raw = params["npd_formulation_uuid"] || params[:npd_formulation_uuid]

    case raw do
      s when is_binary(s) and s != "" ->
        case Ecto.UUID.cast(s) do
          {:ok, uuid} -> {:ok, uuid}
          :error -> {:error, :invalid_uuid}
        end

      _ ->
        {:error, :missing_uuid}
    end
  end

  defp sanitize(nil), do: nil
  defp sanitize(""), do: nil
  defp sanitize(v) when is_binary(v), do: String.trim(v)
  defp sanitize(_), do: nil

  # Sample CO title: ``"<Formulation name> · Sample #<N>"`` where N is
  # a per-formulation sequential counter (the 47th customer to order
  # RTG00001 gets ``"Ultimate Fat Burner Drink · Sample #47"``).
  # ``#1`` for the first order — that customer sees no confusing "#0".
  #
  # Formulation-name preference:
  #   1. explicit ``formulation_name`` from the payload
  #   2. stripped ``sample_label`` — often already "Sample · <name>",
  #      trim the leading "Sample · " so we don't double it
  #   3. ``formulation_code`` as a last resort ("RTG00001")
  #
  # Falls back to a generic ``"Sample #<N>"`` when nothing resolves.
  defp build_sample_reference(company_id, params) do
    formulation_name =
      formulation_display_name(params) || fallback_reference(params)

    sequence = next_sample_sequence(company_id, params)

    case {formulation_name, sequence} do
      {nil, nil} -> nil
      {nil, n} -> "Sample ##{n}"
      {name, nil} -> name
      {name, n} -> "#{name} · Sample ##{n}"
    end
  end

  defp formulation_display_name(params) do
    raw_name = sanitize(params["formulation_name"] || params[:formulation_name])
    raw_code = sanitize(params["formulation_code"] || params[:formulation_code])

    cond do
      # NPD sometimes ships the code as the name when the scientist
      # hasn't renamed the RTG. In that case fall through to the
      # sample_label parse — it's usually more human.
      raw_name && raw_name != raw_code ->
        raw_name

      true ->
        parse_sample_label(params) || raw_name || raw_code
    end
  end

  defp parse_sample_label(params) do
    case sanitize(params["sample_label"] || params[:sample_label]) do
      nil ->
        nil

      label ->
        # Strip the leading "Sample · " / "Sample - " / "Sample: " so
        # we don't produce "<Sample · Ultimate Fat Burner Drink> ·
        # Sample #47".
        String.replace(label, ~r/^\s*Sample\s*[·:\-–—]\s*/iu, "")
    end
  end

  defp fallback_reference(params), do: reference_for(params)

  # Per-formulation counter: count of existing sample COs with the
  # same ``npd_formulation_uuid`` + 1. Returns ``nil`` when we can't
  # resolve a formulation uuid so the label falls back to plain
  # formulation name (adding "#1" without any anchor reads weirdly).
  defp next_sample_sequence(company_id, params) do
    case extract_uuid(params) do
      {:ok, formulation_uuid} ->
        existing =
          Repo.aggregate(
            from(co in CustomerOrder,
              where:
                co.company_id == ^company_id and
                  co.npd_formulation_uuid == ^formulation_uuid and
                  co.sample_kind == true
            ),
            :count
          )

        existing + 1

      _ ->
        nil
    end
  end

  # Mirror the customer's saved delivery_address (portal profile
  # settings on the website → NPD Customer row → PSP CO). Written on
  # insert always; on update only when the CO is still ``draft`` so
  # an approved commercial order's shipping party can't be silently
  # rewritten by a later re-sync. Sample COs land as ``confirmed`` on
  # first sync but we still allow the address to refresh — samples
  # follow the customer's current portal profile, not a legally
  # frozen contract.
  defp put_customer_delivery_address(changeset, params) do
    case sanitize(
           params["customer_delivery_address"] ||
             params[:customer_delivery_address]
         ) do
      nil -> changeset
      addr -> Ecto.Changeset.put_change(changeset, :delivery_address, addr)
    end
  end

  defp put_customer_delivery_address(changeset, params, "draft"),
    do: put_customer_delivery_address(changeset, params)

  defp put_customer_delivery_address(changeset, params, "confirmed"),
    do: put_customer_delivery_address(changeset, params)

  # Any status past ``confirmed`` → the CO is legally live; freeze
  # the address to what it was when the operator signed off. A late
  # profile edit on the website can't rewrite an approved order's
  # ship-to.
  defp put_customer_delivery_address(changeset, _params, _status),
    do: changeset

  # ==================================================================
  # Sample-fulfilment sync
  # ==================================================================
  #
  # Sibling of ``upsert_from_npd/2``, keyed on ``npd_sample_payment_uuid``
  # instead of ``npd_formulation_uuid``. Used for the sample flow where
  # a customer orders a sample of a formulation (RTG or custom) via the
  # portal, the R&D scientist creates a sample trial batch on NPD, and
  # then clicks *Create MO on PSP*. NPD hits this path first so PSP
  # knows the customer + sample identity, then creates the MO.
  #
  # Why a separate identity key from the formulation sync:
  #
  #   * A single RTG formulation is ordered by many customers. If we
  #     re-used ``npd_formulation_uuid`` the second customer's sample
  #     would overwrite the first one's CO. Keying on the sample
  #     payment (unique per customer + order) gives us one CO per
  #     sample fulfilment, all attached to the correct PSP customer.
  #   * Custom-formulation samples also key on the payment for
  #     symmetry — the commercial CO (formulation-keyed) is a
  #     different project entirely and shouldn't get mixed with
  #     sample runs.
  #
  # CO shape produced:
  #
  #   * ``uuid = npd_sample_payment_uuid`` — same URL on both sides.
  #   * ``status = "confirmed"`` — samples skip the PSP approval
  #     wizard; the customer already paid on NPD, PSP just runs it.
  #   * ``sample_kind = true`` — /projects renders a chip on the row.
  #   * ``customer_reference = sample_label`` — the scientist-typed
  #     label from ``TrialBatch.label`` (e.g. "Sample · Alex Gummies").
  #   * ``customer_id`` resolved via the shared ``resolve_customer``
  #     helper — dedupes by ``npd_source_uuid`` fast path, name-match
  #     soft dedupe, only creates fresh when nothing matches.
  #   * One ``CustomerOrderLine`` for the sample item.

  @doc """
  Upsert a sample CO + line from an NPD sample-payment payload.

  Payload shape:

      %{
        "npd_sample_payment_uuid" => "…uuid…",
        "customer_uuid"           => "…npd customer uuid…",
        "customer_display_name"   => "Alex Baker",
        "sample_label"            => "Sample · Ultimate Fat Burner Drink",
        "item_uuid"               => "…psp item uuid…",
        "quantity"                => "1",
        "formulation_name"        => "Ultimate Fat Burner Drink" (optional),
        "formulation_code"        => "RTG00001"                  (optional),
        "lead_scientist_name"     => "…"                         (optional),
        "sales_person_name"       => "…"                         (optional),
        "app_url"                 => "…deep link back to NPD…"   (optional),
        "notes"                   => "…"                         (optional)
      }

  Returns ``{:ok, %CustomerOrder{}}`` on success. Runs the customer
  upsert + CO upsert + line insert in one transaction so we never
  land in a state with a CO but no line (or a line pointing at a
  half-built CO).
  """
  def upsert_sample_from_npd(company_id, params) when is_integer(company_id) do
    with {:ok, sample_uuid} <- extract_sample_uuid(params),
         {:ok, item} <- resolve_item(company_id, params) do
      Repo.transaction(fn ->
        placeholder = ensure_placeholder_customer(company_id)
        active_customer = resolve_customer(company_id, placeholder, params)

        result =
          case Repo.get_by(CustomerOrder,
                 company_id: company_id,
                 uuid: sample_uuid
               ) do
            nil ->
              insert_sample_new(
                company_id,
                active_customer,
                sample_uuid,
                item,
                params
              )

            existing ->
              update_sample_existing(existing, active_customer, params)
          end

        case result do
          {:ok, co} -> co
          {:error, cs} -> Repo.rollback(cs)
        end
      end)
    end
  end

  defp insert_sample_new(company_id, active_customer, sample_uuid, item, params) do
    now = DateTime.utc_now() |> DateTime.truncate(:second)

    ref = build_sample_reference(company_id, params)

    attrs = %{
      company_id: company_id,
      customer_id: active_customer.id,
      currency_code: active_customer.currency_code || "GBP",
      customer_reference: ref,
      notes: sanitize(params["notes"] || params[:notes]),
      inserted_at: now,
      updated_at: now
    }

    # ``uuid`` planted from the sample payment so the same identifier
    # opens the same entity on both apps. ``status`` + ``sample_kind``
    # + the NPD mirror fields aren't in the base cast list, so
    # ``put_change`` them here.
    changeset =
      %CustomerOrder{uuid: sample_uuid}
      |> CustomerOrder.changeset(attrs)
      |> Ecto.Changeset.put_change(:status, "confirmed")
      |> Ecto.Changeset.put_change(:confirmed_at, now)
      |> Ecto.Changeset.put_change(:sample_kind, true)
      |> put_npd_formulation_uuid(params)
      |> put_npd_team(params)
      |> put_npd_payment(params)
      |> put_customer_delivery_address(params)

    with {:ok, co} <- Repo.insert(changeset),
         {:ok, _line} <- insert_sample_line(co, item, params) do
      {:ok, co}
    end
  end

  defp update_sample_existing(%CustomerOrder{} = existing, active_customer, params) do
    sample_label = sanitize(params["sample_label"] || params[:sample_label])

    attrs = %{
      customer_reference:
        sample_label || reference_for(params) || existing.customer_reference,
      notes: sanitize(params["notes"] || params[:notes]) || existing.notes
    }

    # Samples are already ``confirmed`` on first sync; still gate the
    # customer swap on ``draft`` to match commercial semantics — once
    # a sample is running on PSP, we don't want a stray re-sync to
    # switch its billing party.
    changeset =
      existing
      |> CustomerOrder.changeset(attrs)
      |> put_npd_formulation_uuid(params)
      |> put_npd_team(params)
      |> put_npd_payment(params)
      |> put_customer_delivery_address(params, existing.status)

    changeset =
      if existing.status == "draft" and existing.customer_id != active_customer.id do
        Ecto.Changeset.put_change(changeset, :customer_id, active_customer.id)
      else
        changeset
      end

    Repo.update(changeset)
  end

  # Idempotent line insert — a re-sync doesn't add another line. The
  # only line on a sample CO is the sample itself; if it's already
  # there we leave it alone (the scientist may have adjusted qty on
  # PSP-side and we don't want to overwrite that).
  defp insert_sample_line(%CustomerOrder{} = co, %Item{} = item, params) do
    existing =
      Repo.one(
        from l in CustomerOrderLine,
          where: l.customer_order_id == ^co.id,
          limit: 1
      )

    case existing do
      %CustomerOrderLine{} = line ->
        {:ok, line}

      nil ->
        qty = parse_qty(params["quantity"] || params[:quantity])

        %CustomerOrderLine{}
        |> CustomerOrderLine.changeset(%{
          customer_order_id: co.id,
          company_id: co.company_id,
          item_id: item.id,
          qty_ordered: qty,
          unit_price: Decimal.new(0)
        })
        |> Repo.insert()
    end
  end

  defp extract_sample_uuid(params) do
    raw = params["npd_sample_payment_uuid"] || params[:npd_sample_payment_uuid]

    case raw do
      s when is_binary(s) and s != "" ->
        case Ecto.UUID.cast(s) do
          {:ok, uuid} -> {:ok, uuid}
          :error -> {:error, :invalid_sample_uuid}
        end

      _ ->
        {:error, :missing_sample_uuid}
    end
  end

  defp resolve_item(company_id, params) do
    raw = params["item_uuid"] || params[:item_uuid]

    with s when is_binary(s) and s != "" <- raw,
         {:ok, uuid} <- Ecto.UUID.cast(s),
         %Item{} = item <-
           Repo.one(
             from i in Item,
               where: i.company_id == ^company_id and i.uuid == ^uuid,
               limit: 1
           ) do
      {:ok, item}
    else
      _ -> {:error, :item_not_found}
    end
  end

  defp parse_qty(nil), do: Decimal.new(1)
  defp parse_qty(v) when is_integer(v), do: Decimal.new(v)
  defp parse_qty(%Decimal{} = v), do: v

  defp parse_qty(v) when is_binary(v) do
    case Decimal.parse(v) do
      {d, _} -> d
      :error -> Decimal.new(1)
    end
  end

  defp parse_qty(_), do: Decimal.new(1)

  # Mirror NPD's Payment record onto the CO (metadata + files list).
  # NPD sends the payload as ``payment: %{id, amount, currency,
  # invoice_number, paid_at, status, files: [...]}`` on every
  # sample sync so PSP's CO detail can render the payment card
  # instead of "No invoice attached".
  #
  # ``files`` is a list of ``%{uuid, filename, mime, byte_size,
  # uploaded_at}`` maps — bytes stay on NPD; the CO detail card
  # renders filenames + metadata only. Falls back to ``[]`` on
  # missing / malformed lists so a bad payload doesn't blow up
  # the whole sync transaction.
  # Persist the NPD formulation uuid on a sample CO so downstream
  # PSP flows (wizard "Create MO for line", R&D validation gate,
  # NPD trial-batch reverse lookup) all know which formulation this
  # sample maps to. Commercial COs get the same field via the
  # ``upsert_from_npd`` path — this helper closes the sample-flow
  # gap where the earlier code created the CO without the linkage,
  # stranding wizard-created MOs from ever reaching NPD validation.
  defp put_npd_formulation_uuid(changeset, params) do
    raw = params["npd_formulation_uuid"] || params[:npd_formulation_uuid]

    case raw do
      s when is_binary(s) and s != "" ->
        case Ecto.UUID.cast(s) do
          {:ok, uuid} -> Ecto.Changeset.put_change(changeset, :npd_formulation_uuid, uuid)
          :error -> changeset
        end

      _ ->
        changeset
    end
  end

  defp put_npd_payment(changeset, params) do
    payment = params["payment"] || params[:payment]

    case payment do
      %{} = pay ->
        changeset
        |> maybe_put_uuid(:npd_payment_id, pay["id"] || pay[:id])
        |> maybe_put_decimal(:npd_payment_amount, pay["amount"] || pay[:amount])
        |> maybe_put(:npd_payment_currency, sanitize(pay["currency"] || pay[:currency]))
        |> maybe_put(:npd_payment_invoice_number, sanitize(pay["invoice_number"] || pay[:invoice_number]))
        |> maybe_put_dt(:npd_payment_paid_at, pay["paid_at"] || pay[:paid_at])
        |> maybe_put(:npd_payment_status, sanitize(pay["status"] || pay[:status]))
        |> put_npd_payment_files(pay["files"] || pay[:files])

      _ ->
        changeset
    end
  end

  defp put_npd_payment_files(changeset, files) when is_list(files) do
    # Normalise each row so the FE never has to defend against
    # missing keys. Bad entries (non-map) are dropped.
    normalised =
      Enum.flat_map(files, fn
        %{} = f ->
          [
            %{
              "uuid" => to_string(f["uuid"] || f[:uuid] || ""),
              "filename" => to_string(f["filename"] || f[:filename] || ""),
              "mime" => to_string(f["mime"] || f[:mime] || ""),
              "byte_size" => f["byte_size"] || f[:byte_size] || 0,
              "uploaded_at" => to_string(f["uploaded_at"] || f[:uploaded_at] || "")
            }
          ]

        _ ->
          []
      end)

    Ecto.Changeset.put_change(changeset, :npd_payment_files, normalised)
  end

  defp put_npd_payment_files(changeset, _), do: changeset

  defp maybe_put_decimal(changeset, _field, nil), do: changeset
  defp maybe_put_decimal(changeset, _field, ""), do: changeset

  defp maybe_put_decimal(changeset, field, %Decimal{} = d),
    do: Ecto.Changeset.put_change(changeset, field, d)

  defp maybe_put_decimal(changeset, field, v) when is_binary(v) do
    case Decimal.parse(v) do
      {d, _} -> Ecto.Changeset.put_change(changeset, field, d)
      :error -> changeset
    end
  end

  defp maybe_put_decimal(changeset, field, v) when is_integer(v),
    do: Ecto.Changeset.put_change(changeset, field, Decimal.new(v))

  defp maybe_put_decimal(changeset, _field, _), do: changeset
end
