defmodule BackendWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :backend

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  #
  # `secure` is forced true in prod (cookie MUST NOT flow over HTTP),
  # left false in dev where localhost may serve plain HTTP.
  # `http_only` is Plug's default true — kept explicit.
  # `same_site: "Strict"` — API is JSON-only, no cross-site form
  # submissions ever need to arrive with cookies.
  @session_options [
    store: :cookie,
    key: "_backend_key",
    signing_salt: "V2LiJ4lN",
    http_only: true,
    secure: Mix.env() == :prod,
    same_site: "Strict"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Realtime presence socket — JS client connects with `?token=<bearer>`
  # immediately after login.
  #
  # `check_origin` is a compile-time knob; we override at runtime.exs
  # for :prod so the deployed instance rejects WS upgrades from any
  # host other than the configured PHX_HOST. Left `false` here for dev
  # so localhost / LAN cross-origin upgrades still work while running
  # `mix phx.server`.
  # Prod overrides `check_origin` at runtime via `config/runtime.exs`
  # using PHX_HOST + WS_EXTRA_ORIGINS — dev is deliberately open so
  # LAN devices (paired phones) can join without additional config.
  socket "/socket", BackendWeb.UserSocket,
    # Dev: `check_origin: false` so cross-origin WS upgrades from LAN
    # devices (phones on Wi-Fi, the `.local` hostname the FE serves
    # from) succeed without hard-coding every host. Prod overrides
    # this at runtime in `config/runtime.exs` using PHX_HOST +
    # WS_EXTRA_ORIGINS, so the deployed instance still rejects
    # upgrades from unrelated hosts.
    websocket: [check_origin: false],
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :backend,
    gzip: not code_reloading?,
    only: BackendWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :backend
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # CORS — allowed origins come from `Backend.Config.cors_origins/1`,
  # which reads the `CORS_ORIGINS` env var at runtime. That means prod
  # deploys can rotate origins by env-var change alone; no recompile.
  # CORSPlug 3.0.3 accepts a function reference (arity 1, taking conn)
  # and calls it per request — the closure survives plug-init because
  # `plug` doesn't `Macro.escape` its options.
  plug CORSPlug,
    origin: &Backend.Config.cors_origins/1,
    credentials: false,
    max_age: 86_400

  # Global upload/body cap. Per-endpoint app-level limits still apply
  # (e.g. 5-25 MB), but this bounds the raw multipart buffer so a client
  # can't stream 10 GB before the app rejects it. 100 MB = generous
  # headroom for BMR PDFs / receipt evidence bundles.
  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    length: 100_000_000,
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug BackendWeb.Router
end
